package com.hyve.ui.core.domain.elements

import com.hyve.ui.core.id.ElementId

/**
 * Prefix for auto-generated element IDs.
 *
 * Elements in .ui files often lack explicit IDs (e.g., `Group { Label { } }`).
 * The editor's delta-based export pipeline requires IDs to track structural
 * changes (move, delete, reparent). This prefix marks IDs that were assigned
 * automatically and should be stripped during export.
 */
const val AUTO_ID_PREFIX = "_auto_"

/**
 * Check if an [ElementId] was auto-generated by the editor.
 * Auto-generated IDs are stripped during export to keep .ui files clean.
 */
fun ElementId.isAutoGenerated(): Boolean = value.startsWith(AUTO_ID_PREFIX)

/**
 * Assigns deterministic auto-generated IDs to all elements that lack an explicit ID.
 *
 * Uses depth-first traversal so the same source text always produces the same
 * auto-IDs, regardless of which parser (raw vs resolved) processed it.
 * This is critical for the dual-document architecture: deltas recorded against
 * the resolved (visual) tree must match elements in the raw (export) tree.
 *
 * Auto-IDs use the format `_auto_{Type}_{counter}` for debuggability.
 *
 * @return A copy of this element tree with auto-IDs assigned to all ID-less elements.
 *         Elements that already have IDs are left unchanged.
 */
fun UIElement.assignAutoIds(): UIElement {
    var counter = 0

    fun assign(element: UIElement): UIElement {
        val id = element.id ?: ElementId("$AUTO_ID_PREFIX${element.type.value}_${counter++}")
        val newChildren = element.children.map { assign(it) }
        return element.copy(id = id, children = newChildren)
    }

    return assign(this)
}
